openapi: 3.0.0
info:
  title: Mi API
  version: 1.0.0
  description: Descripción de mi API
paths:
  /cantantes:
    get:
      summary: Obtiene todos los cantantes
      responses:
        '200':
          description: Éxito
